CREATE TABLE IF NOT EXISTS goals (
    goal_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    stand ENUM('NOT_STARTED', 'PROGRESS', 'COMPLETED', 'OVERDUE') NOT NULL DEFAULT 'NOT_STARTED',
    due_date TIMESTAMP DEFAULT NULL,
    CONSTRAINT fk_goal_user FOREIGN KEY (goal_user) REFERENCES users(id)
);